### ISSUE TITLE
ExplorerPatcher会导致守望先锋会崩溃

### ISSUE THREAD

**Issue by iomect** [ZetaSp/ExplorerPatcher#12]
守望先锋一直崩溃，经过两天总共10多个小时的排除法测试，最终发现是ExplorerPatcher导致的，无论是您的中文版还是原英文版都会导致守望先锋报错崩溃。
守望先锋的报错提示为：EXCEPTION_ACCESS_VIOLATION reading from 0x000001795e9a5ab0
崩溃前的log为：
[ERR] [bnl] [External(0)] [External()] [2022-10-28T02:06:20.510Z]: PathOps: [20221028T10:06:20] {2818} ERR: .. is the leading path component: /../.build.info
[ERR] [bnl] [External(0)] [External()] [2022-10-28T02:06:20.510Z]: PathOps: [20221028T10:06:20] {2818} ERR: path normalization failed: /../.build.info

原英文版无法提交issue，只好提交到您这里了。
报错时使用的版本为22621.608.51.3，接下来我会继续测试下之前的版本会不会不引起崩溃，希望可以解决。

**Comment by ZetaSp** [comment]
您好，感谢反馈，很抱歉造成了使用上的困扰，不过我没办法解决QAQ
我也不能反馈到原作者，他关闭了github的反馈通道，试试邮件？
valentingabrielradu@gmail.com
