### ISSUE TITLE
未来能支持Mac版吗？

### ISSUE THREAD

**Issue by hoochanlon** [ZetaSp/ExplorerPatcher#19]
点开会白屏，大神可以升级成支持Windows 11 22H2版的软件吗

<img width="1468" alt="catch2023-02-11 17 35 03" src="https://user-images.githubusercontent.com/35732922/218251394-2fef80c9-eb28-47bd-a7ad-040a15e2e95e.png">

<img width="1552" alt="catch2023-02-11 17 37 18" src="https://user-images.githubusercontent.com/35732922/218251398-ba4278c0-8664-4620-8b74-81f5f1a2ed7f.png">

**Comment by ZetaSp** [comment]
Win11是Paralle Desktop的虚拟机吗？虚拟机的话，应该和Win11原版是一致的，可能是这个版本不支持的原因。
我是汉化翻译，原作者已经三个月没更新了，支持Win11新版本需要原作者适配，我还在了解相关进展。

**Comment by ZetaSp** [comment]
ExplorerPatcher的修改稳定性不高，如果您迫切需要这样的功能，可以尝试旧版、官方版，或者其他类似软件

**Comment by hoochanlon** [comment]
是PD的win11。
目前也什么工具代替菜单的。

发自我的 iPad

在 2023年2月12日，16:57，Zetaspace ***@***.***> 写道：

﻿

ExplorerPatcher的修改稳定性不高，如果您迫切需要这样的功能，可以尝试旧版、官方版，或者其他类似软件

**Comment by hoochanlon** [comment]
大佬有兴趣做卸载软件的汉化吗？

Bulk-Crap-Uninstaller：https://github.com/Klocman/Bulk-Crap-Uninstaller

**Comment by ZetaSp** [comment]
> 大佬有兴趣做卸载软件的汉化吗？
> 
> Bulk-Crap-Uninstaller：https://github.com/Klocman/Bulk-Crap-Uninstaller

有兴趣看看，不过同类软件比如 Uninstall Tool（有中文）也有不少，而且 BCU 好像目前缺少维护的样子是吗？
等我几周，做好了叫你哦
现在在学校里可能时间不太够

**Comment by hoochanlon** [comment]
> > 大佬有兴趣做卸载软件的汉化吗？
> > Bulk-Crap-Uninstaller：https://github.com/Klocman/Bulk-Crap-Uninstaller
> 
> 有兴趣看看，不过同类软件比如 Uninstall Tool（有中文）也有不少，而且 BCU 好像目前缺少维护的样子是吗？ 等我几周，做好了叫你哦 现在在学校里可能时间不太够

也还好吧，最近更新是六月份的。主要是其他的卸载软件并不是免费的，基本上都是付费。

**Comment by czz404** [comment]
> 大佬有兴趣做卸载软件的汉化吗？
> 
> Bulk-Crap-Uninstaller：https://github.com/Klocman/Bulk-Crap-Uninstaller

这个软件有中文的

**Comment by ZetaSp** [comment]
> > 大佬有兴趣做卸载软件的汉化吗？
> > Bulk-Crap-Uninstaller：https://github.com/Klocman/Bulk-Crap-Uninstaller
> 
> 这个软件有中文的

谢谢，看到了
