### ISSUE TITLE
Incompatibilities always present bugs

### ISSUE THREAD

**Issue by sekiro051** [ZetaSp/ExplorerPatcher#20]
The version of my system is as follows：Windows 11 version，22H2，22621.1265，Windows Feature Experience Pack 1000.22638.1000.0
I used to use the 22h2 version of win11, but it was the home version, that was I ran it without problems, but I forgot which version of ExplorerPatcher I was running, and now I have run multiple versions of ExplorerPatcher and the display flashes white

**Comment by ZetaSp** [comment]
Sorry, but I'm not the original creator of this software.
If you have problems using this software, please try use newer/older version or report to valinet (the creator).
