### ISSUE TITLE
开始菜单切换为win10风格时打不开，版本号22621.1413.54.5

### ISSUE THREAD

**Issue by ze47** [ZetaSp/ExplorerPatcher#22]

**Comment by SheepMoods** [comment]
22621.1413.54.5似乎有较大变动，即使安装了汉化包磁贴的汉化也不完全。

**Comment by ZetaSp** [comment]
请尝试向作者反馈：[ExplorerPatcher issues](https://github.com/valinet/ExplorerPatcher/issues)

**Comment by ZetaSp** [comment]
我这儿EP会导致闪退，无法使用，最新canary

**Comment by SheepMoods** [comment]
我在RP和正式版倒是能正常使用，开始菜单汉化不完整的话多替换几次文件就行。
