### ISSUE TITLE
ExplorerPatcher properties showing in CHINESE language by default

### ISSUE THREAD

**Issue by GauravSahare1993** [ZetaSp/ExplorerPatcher#23]
I am using Windows 11 22H2 (10.0.22621 Build 22621).
I recently downloaded ExplorerPatcher v22621.1413.54.5 Translation 17
when I installed ExplorerPatcher 1st time, then I faced 2 major problems.
1. Resources are not downloading because McAfee antivirus (latest and updated version) silently prevents the activity related from resource downloads.
2. Start Menu (left click) were not responding.

So I uninstalled, restarted my PC, disabled McAfee antivirus, then again installed ExplorerPatcher, this time ExplorerPatcher successfully downloaded some resources (but no GUI). 2nd problem has fixed, and ExplorerPatcher works fine but now properties are showing in CHINESE language, which is weird for me because I can't understand CHINESE language.

So I again uninstalled, again restarted, I deleted all the folders of ExplorerPatcher from following directories
C:\Program Files\ExplorerPatcher
C:\Users\USERNAME\AppData\Roaming\ExplorerPatcher

Now I installed ExplorerPatcher, everything works fine but language problem of properties still not fixed.

No matter that users are using Windows 10 or 11, Start Menu related problem should not appear again.
Now tell me how to fix language problem of properties?
![Screenshot (1)](https://user-images.githubusercontent.com/109745579/234193243-43577362-fe3c-4cb9-8ffe-a16a784a2de5.png)

**Comment by ZetaSp** [comment]
I'm sorry, but this is the Chinese modified version.
I think you are looking for the original English version: [HERE](https://github.com/valinet/ExplorerPatcher)

**Comment by ZetaSp** [comment]
Thank you for your reminder, I will add more words to inform users that this is a modified version of the Chinese localization, not the original English version.
