### ISSUE TITLE
16版本出现严重闪退，退回15版本恢复正常

### ISSUE THREAD

**Issue by f59375543** [ZetaSp/ExplorerPatcher#5]
这是我的配置文件

[ExplorerPatcher_22622.450.50.2.reg.zip](https://github.com/ZetaSp/ExplorerPatcher/files/9448709/ExplorerPatcher_22622.450.50.2.reg.zip)

**Comment by ZetaSp** [comment]
16版是原储存库的测试版，可能是原版的不稳定造成。现已将汉化16调整为测试版，正式版退回15。

**Comment by ZetaSp** [comment]
该版本在我的win11 dev电脑上没有出现问题，你可以试试向原作者反馈
