### ISSUE TITLE
开始菜单部分内容还是英文

### ISSUE THREAD

**Issue by auyo18** [ZetaSp/ExplorerPatcher#6]
![1662177991472](https://user-images.githubusercontent.com/23635064/188255252-07be6e83-38ce-4df6-9a8c-a971e79ff05d.png)
![image](https://user-images.githubusercontent.com/23635064/188255276-b187b624-a307-4c1b-a23d-467798511b0f.png)

**Comment by ZetaSp** [comment]
开始菜单是从微软下载的系统组件，目前暂时没找到汉化方法

**Comment by meiruitesi** [comment]
我有：
先换回win11的开始菜单，然后把
[epwin10startCN.zip](https://github.com/ZetaSp/ExplorerPatcher/files/9482722/epwin10startCN.zip)
中的文件复制到
%SystemRoot%\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy
下（报重复文件时选替换）即可

**Comment by meiruitesi** [comment]
附图
![image](https://user-images.githubusercontent.com/84609642/188273804-07439506-9afb-4773-aadc-30b93a40bc89.png)
![image](https://user-images.githubusercontent.com/84609642/188273816-65586220-363d-4e82-aabd-83d80503089f.png)

**Comment by ZetaSp** [comment]
> 我有： 先换回win11的开始菜单，然后把 [epwin10startCN.zip](https://github.com/ZetaSp/ExplorerPatcher/files/9482722/epwin10startCN.zip) 中的文件复制到 %SystemRoot%\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy 下（报重复文件时选替换）即可

谢谢！会考虑加上这个辅助汉化。请问这个文件的来源是？是否有更新地址呢？
现在在学校暂时不方便，下周周末去做。

**Comment by meiruitesi** [comment]
> > 我有： 先换回win11的开始菜单，然后把 [epwin10startCN.zip](https://github.com/ZetaSp/ExplorerPatcher/files/9482722/epwin10startCN.zip) 中的文件复制到 %SystemRoot%\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy 下（报重复文件时选替换）即可
> 
> 谢谢！会考虑加上这个辅助汉化。请问这个文件的来源是？是否有更新地址呢？ 现在在学校暂时不方便，下周周末去做。

Windows.UI.ShellCommon.zh-CN.pri是从win10的镜像里提取的，StartTileDataLegacy.dll.mui是我自己用ResHacker手工汉化的（
顺便，StartTileDataLegacy.dll.en_US.mui和Windows.UI.ShellCommon.en-US.pri是我打包时忘了把英文原版文件删了（

**Comment by ZetaSp** [comment]
[ExplorerPatcher补充汉化.zip](https://github.com/ZetaSp/ExplorerPatcher/files/9639911/ExplorerPatcher.zip)

**Comment by zetaloop** [comment]
@meiruitesi @huashengqiaobeili 你给的 Windows.UI.ShellCommon.zh-CN.pri 文件，大小 100KB，拆包确认部分中文字串缺失，可能是因为提取的系统版本不对？
我从 [bbmaster123/10SM](https://github.com/bbmaster123/10SM) 项目找到了完整的 .pri 文件，大小 131KB

**Comment by meiruitesi** [comment]
> @meiruitesi @huashengqiaobeili 你给的 Windows.UI.ShellCommon.zh-CN.pri 文件，大小 100KB，拆包确认部分中文字串缺失，可能是因为提取的系统版本不对？ 我从 [bbmaster123/10SM](https://github.com/bbmaster123/10SM) 项目找到了完整的 .pri 文件，大小 131KB

我说了，这个东西是我自己手动汉化的，所以当然会有些问题啦（

**Comment by zetaloop** [comment]
> > @meiruitesi @huashengqiaobeili 你给的 Windows.UI.ShellCommon.zh-CN.pri 文件，大小 100KB，拆包确认部分中文字串缺失，可能是因为提取的系统版本不对？ 我从 [bbmaster123/10SM](https://github.com/bbmaster123/10SM) 项目找到了完整的 .pri 文件，大小 131KB
> 
> 我说了，这个东西是我自己手动汉化的，所以当然会有些问题啦（

好消息，被念叨了超级久的开始菜单缺汉化问题终于解决了~
[补充汉化v2.0.zip](https://github.com/zetaloop/ExplorerPatcher/files/12028650/v2.0.zip)

**Comment by zetaloop** [comment]
[v3.0.zip](https://github.com/zetaloop/ExplorerPatcher/files/12137341/v3.0.zip)

保留从 10SM 拿来的 Windows.UI.ShellCommon.zh-CN.pri，其余文件改为建立符号链接到 System32 中的原版中文文件。
根据 https://github.com/valinet/ExplorerPatcher/issues/1108 https://github.com/valinet/ExplorerPatcher/issues/1591 添加了**修复 Win10 开始菜单不显示 UWP 应用**。

目前修复完成后，**“固定到开始菜单”功能将会失效**，但是可以拖动来固定。

删除磁贴可以通过取消固定组来取消固定（来自原issue）：

https://github.com/zetaloop/ExplorerPatcher/assets/36418285/873bf111-c722-4fac-964a-d2ab416de250

**Comment by Erosionone** [comment]
> [v3.0.zip](https://github.com/zetaloop/ExplorerPatcher/files/12137341/v3.0.zip)
> 
> 保留从 10SM 拿来的 Windows.UI.ShellCommon.zh-CN.pri，其余文件改为建立符号链接到 System32 中的原版中文文件。 根据 [valinet/ExplorerPatcher#1108](https://github.com/valinet/ExplorerPatcher/issues/1108) [valinet/ExplorerPatcher#1591](https://github.com/valinet/ExplorerPatcher/issues/1591) 添加了**修复 Win10 开始菜单不显示 UWP 应用**。
> 
> 目前修复完成后，**“固定到开始菜单”功能将会失效**，但是可以拖动来固定。
> 
> 删除磁贴可以通过取消固定组来取消固定（来自原issue）：
> 
>  bandicam.2023-07-23.07-43-16-874.mp4

这个v3.0怎么卸载啊？valinet那边更新了，装完新版本之后还是不能直接取消固定

**Comment by zetaloop** [comment]
@Erosionone 该修补包执行的所有覆盖操作都备份了原文件，可以随时撤回，只需要执行相反的操作。
不过，valinet 的解决方案和修补包是一样的，都是替换 win10 版 AppResolverLegacy 和 StartTileDataLegacy 为 win11 新版，启用新功能但导致 “固定到开始菜单” 功能由于数据结构更新而不能使用。
请参考 valinet 的说明：https://github.com/valinet/ExplorerPatcher/discussions/1679

### 卸载修补包（v3.0）
打开 `C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txye`
删除 zh-CN 文件夹（符号链接）
删除 AppResolverLegacy.dll（符号链接），重命名时间最早的一个 AppResolverLegacy.dll.xxxx.bak 为 AppResolverLegacy.dll
删除 StartTileDataLegacy.dll（符号链接），重命名时间最早的一个 StartTileDataLegacy.dll.xxxx.bak 为 StartTileDataLegacy.dll
删除 pris2 文件夹内的 Windows.UI.ShellCommon.zh-CN.pri 文件

**Comment by Erosionone** [comment]
> @Erosionone 该修补包执行的所有覆盖操作都备份了原文件，可以随时撤回，只需要执行相反的操作。 不过，valinet 的解决方案和修补包是一样的，都是替换 win10 版 AppResolverLegacy 和 StartTileDataLegacy 为 win11 新版，启用新功能但导致 “固定到开始菜单” 功能由于数据结构更新而不能使用。 请参考 valinet 的说明：[valinet/ExplorerPatcher#1679](https://github.com/valinet/ExplorerPatcher/discussions/1679)
> 
> ### 卸载修补包（v3.0）
> 打开 `C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txye` 删除 zh-CN 文件夹（符号链接） 删除 AppResolverLegacy.dll（符号链接），重命名时间最早的一个 AppResolverLegacy.dll.xxxx.bak 为 AppResolverLegacy.dll 删除 StartTileDataLegacy.dll（符号链接），重命名时间最早的一个 StartTileDataLegacy.dll.xxxx.bak 为 StartTileDataLegacy.dll 删除 pris2 文件夹内的 Windows.UI.ShellCommon.zh-CN.pri 文件

好的，感谢❤
