### ISSUE TITLE
Live Tiles Anywhere创建的磁贴无法固定到win10开始菜单。

### ISSUE THREAD

**Issue by nljxlove** [ZetaSp/ExplorerPatcher#7]
Live Tiles Anywhere创建的磁贴无法固定到win10开始菜单。同样的，在应用商店里点击固定到开始菜单依然不行，只有在win10开始菜单的列表里去固定磁贴。

**Comment by ZetaSp** [comment]
这好像是这款软件的通病，你试试去其他论坛和原作者那里找找有没有解决方案

**Comment by ZetaSp** [comment]
我只是个汉化的，修bug修不来
