### ISSUE TITLE
鼠标右键任务栏不弹出菜单而闪屏

### ISSUE THREAD

**Issue by sekiro051** [ZetaSp/ExplorerPatcher#8]
最近这次win更新后就出现鼠标右键任务栏的时候不弹出菜单而是突然桌面空白闪一下卸载重装也没用，这是啥情况啊求问

**Comment by nljxlove** [comment]
先安装一次预发行版，再覆盖安装最新版即可。

**Comment by ZetaSp** [comment]
你好。问题解决了吗？如果已经解决的话，我就把issue关闭了
